### ISSUE TITLE
Support sn8encode5 format

### ISSUE THREAD

**Issue by C0rn3j** [Marisa-Chan/sn8dis#1]
A4 released a new firmware format which does not have plaintext information at the top of the firmware files anymore, making the tool output "Unknown chip 4V3!" in the .asm.

[sn8encode4&5.zip](https://github.com/Marisa-Chan/sn8dis/files/3600074/sn8encode4.5.zip)

**Comment by Marisa-Chan** [comment]
Seems they make cleanup of firmwares. Now it's zeroed compiler info
(0x0-0x100) bloody bootblock (0x100-0x300) and data in the end of the
firmware. You always can make list with firmware name == chip name. Also
you can do identify of chip by creating some signatures like some commands
that always are same for different firmwares(distance between that
commands) and get bytes for them (without data bits) and use size of
firmware as additional identify.



ср, 11 сент. 2019 г. в 16:49, Martin <notifications@github.com>:

**Comment by C0rn3j** [comment]
I did as you suggested and matched firmware names to chip names based on sn8encode4.

Not all firmwares have an older version with the chip available so I ended up with this list at the moment:
```yaml
A80cir_A3050_160: {Chip: SN8F22E84B}
ALcir_A9800_0E4: {Chip: SN8F2288}
Acir2_A3050_0B4: {Chip: SN8F2288}
Acir_A3050Korea_298: {Chip: SN8F2288}
Acir_A3050_0E0: {Chip: SN8F2288}
Acir_A3050_184: {Chip: SN8F22E84B}
Air2_A3050_05C: {Chip: SN8F2288}
Air_A3050_038: {Chip: SN8F2288}
BR220_SN26E68L_16: {Chip: SN8F26E68L}
BR830_A7127_C0: {Chip: SN8F22E88B}
DongleM_SN8F2251B_040: {Chip: SN8F2251B}
DongleM_SN8F22E83B_14C: {Chip: SN8F22E83B}
FF_A3050_03C: {Chip: SN8F2288}
FL_A9800_01C: {Chip: SN8F2288}
FLc_A9800_030: {Chip: SN8F2288}
F_A3050_014: {Chip: SN8F2288}
Fc2_A3050_054: {Chip: SN8F2288}
Fc_A3050_034: {Chip: SN8F2288}
J81c_P3325_498: {Chip: SN8F22E84B}
J82c_P3325_4A0: {}
J86Qc_A3050_2E4: {Chip: SN8F22E84B}
J86c_A3050_2F0: {Chip: SN8F22E84B}
J90S_P3332S_4E4: {}
J90c_P3325_480: {Chip: SN8F22E84B}
J95ProRc_P3360USA_2DC: {Chip: SN8F22E88B}
J95S_P3332S_4E0: {}
J95c_P3325_2E0: {Chip: SN8F22E84B}
J95cir_P3325_490: {Chip: SN8F22E88B}
ML_A9800_0A8: {Chip: SN8F2288}
MLcir_A9800_0F4: {Chip: SN8F2288}
N80cir_A3050_16C: {Chip: SN8F22E84B}
N81c_A3050_4B4: {}
Ncir_A3050_164: {Chip: SN8F22E84B}
P80cir_P3325_1E0: {Chip: SN8F22E84B}
P81ProRcir_P3360_2D0: {Chip: SN8F22E88B}
P88Rcir_P3325Korea_294: {Chip: SN8F22E84B}
P88Rcir_P3325_218: {Chip: SN8F22E84B}
P91MaxRcir_P3332_4CC: {}
P91ProRcir_P3332_4CC: {}
P91ProRcir_P3389_4A4: {}
P91Rcir2_P3332S_4D8: {}
P91Rcir_P3332S_4C0: {}
P91SRcir_P3332S_4C0: {}
P96ProRcir_P3389_4A4: {}
PL81Rcir_A9800_2D4: {Chip: SN8F22E88B}
Q_P3305_078: {Chip: SN8F2253B}
RT62ir_P3325_1CC: {Chip: SN8F22E87B}
RT_A3050_BC: {Chip: SN8F27E65L}
RTir_P3325_C4: {Chip: SN8F22E87B}
R_A3050_B2: {Chip: SN8F27E64L}
R_P3305_2B: {Chip: SN8F27E64L}
Rir_A3050_31: {Chip: SN8F27E65L}
Rir_P3325_C5: {Chip: SN8F22E87B}
S90ProRcir_P3360_2B0: {Chip: SN8F22E88B}
S90ProRcir_P3389_2B0: {}
S90Rcir_P3325_234: {Chip: SN8F22E84B}
S93ProRcir_P3360_2B4: {Chip: SN8F22E88B}
S93ProRcir_P3389_2B4: {}
S93Rcir_P3325_23C: {Chip: SN8F22E84B}
S95ProRcir_P3360_2B8: {Chip: SN8F22E88B}
S95ProRcir_P3389_2B8: {}
SL90Rcir_A9800_2C0: {Chip: SN8F22E88B}
SL93Rcir_A9800_2C4: {Chip: SN8F22E88B}
SP30cir_P3389_4B8: {}
SP80cir_P3389_4BC: {}
TL_A9800_068: {Chip: SN8F2288}
TLcir2_A9800_064: {Chip: SN8F2288}
TLcir_A9800_0EC: {Chip: SN8F2288}
T_A3050_060: {Chip: SN8F2288}
Tcir2_A3050_06C: {Chip: SN8F2288}
Tcir_A3050_0E8: {Chip: SN8F2288}
V3MProcir_P3360_484: {Chip: SN8F22E84B}
V3MProcir_P3389_49C: {}
V9Mc_A3050_4C4: {}
V_A3050_238: {Chip: SN8F22E84B}
V_P3305Korea_290: {Chip: SN8F2253B}
V_P3305_010: {Chip: SN8F2253B}
V_P3307_00C: {Chip: SN8F2253B}
Wir_A3050_1B8: {Chip: SN8F22E87B}
X7cir_P3212_270: {Chip: SN8F22E84B}
ZL_A9800_088: {Chip: SN8F2288}
ZLcir_A9800_0F0: {Chip: SN8F2288}
```
I'll likely post it as mice.yaml  [here](https://gitlab.com/C0rn3j/a4tech_bloody_p85_driver) in some time, so that's where the up to date version will be if someone is reading this a bit in the future.
